import { useState, useCallback, useEffect, useRef } from 'react';
import { PrismLight as SyntaxHighlighter } from 'react-syntax-highlighter';
import sqlLang from 'react-syntax-highlighter/dist/esm/languages/prism/sql';
import jsonLang from 'react-syntax-highlighter/dist/esm/languages/prism/json';
import { oneLight, vscDarkPlus } from 'react-syntax-highlighter/dist/esm/styles/prism';
import { postMsg } from '../vscode';
import './ChangeCard.css';

SyntaxHighlighter.registerLanguage('sql', sqlLang);
SyntaxHighlighter.registerLanguage('json', jsonLang);

export type ChangeData = {
  changeName: string;
  deploySql: string;
  verifySql: string;
  revertSql: string;
  metaJson?: string;
  suggestedLocation?: string;
};

type LintState = { ok: boolean; msg: string } | null;
type SqlTab = 'deploy' | 'verify' | 'revert' | 'meta';

type Props = {
  change: ChangeData;
  form: string;
};

// The form pages unmount while their tab is hidden. Keep what matters about a card — that it
// was saved (so it is not offered for a second save) and unsaved edits — with the change itself.
const cardMemory = new WeakMap<ChangeData, { saved?: { folderRel: string }; editMap?: Partial<Record<SqlTab, string>> }>();

export default function ChangeCard({ change, form }: Props) {
  const [activeTab, setActiveTab] = useState<SqlTab>('deploy');
  const [lintMap, setLintMap] = useState<Record<SqlTab, LintState>>({ deploy: null, verify: null, revert: null, meta: null });
  const [location, setLocation] = useState(change.suggestedLocation || '');
  const [saving, setSaving] = useState(false);
  const [saved, setSavedState] = useState<{ folderRel: string } | null>(() => cardMemory.get(change)?.saved ?? null);
  const setSaved = (v: { folderRel: string } | null) => { cardMemory.set(change, { ...cardMemory.get(change), saved: v ?? undefined }); setSavedState(v); };
  const [saveError, setSaveError] = useState('');
  const [showDiscard, setShowDiscard] = useState(false);
  const [isLightTheme, setIsLightTheme] = useState(() => document.documentElement.dataset.theme === 'light');
  const [editing, setEditing] = useState(false);
  const [editMap, setEditMapState] = useState<Partial<Record<SqlTab, string>>>(() => cardMemory.get(change)?.editMap ?? {});
  const setEditMap = (f: (prev: Partial<Record<SqlTab, string>>) => Partial<Record<SqlTab, string>>) => setEditMapState(prev => { const next = f(prev); cardMemory.set(change, { ...cardMemory.get(change), editMap: next }); return next; });
  const [copied, setCopied] = useState(false);
  const [copiedTab, setCopiedTab] = useState<SqlTab | null>(null);
  const [committing, setCommitting] = useState(false);
  const [commitDone, setCommitDone] = useState(false);
  const [commitError, setCommitError] = useState('');
  // DDL, DML and Freeform pages stay mounted together, so several ChangeCards can be
  // listening at once. Every request carries this id and only matching replies are applied.
  const requestIdRef = useRef(`changecard-${form}-${Math.random().toString(36).slice(2, 10)}`);

  const isDanger = change.changeName?.includes('danger_') ?? false;
  const isRepeatable = change.changeName?.startsWith('R__') ?? false;

  // Build meta.json content
  const metaContent = change.metaJson || JSON.stringify({
    change_id: change.changeName,
    description: `Generated by DMCR ${form} form`,
    requires: [],
    tags: [],
    author: ''
  }, null, 2);

  const sqlMap: Record<SqlTab, string> = {
    deploy: change.deploySql || '',
    verify: change.verifySql || '',
    revert: change.revertSql || '',
    meta: metaContent,
  };

  // Effective SQL for current tab (uses edited version if present)
  const effectiveSql = (tab: SqlTab) => editMap[tab] ?? sqlMap[tab];

  // Request lint for SQL tabs on mount; validate meta.json separately
  useEffect(() => {
    const sqlTabs: SqlTab[] = ['deploy', 'verify', 'revert'];
    sqlTabs.forEach((tab, i) => {
      setTimeout(() => {
        postMsg({ type: 'lintSql', payload: { id: tab, which: tab, sql: sqlMap[tab] || '', requestId: requestIdRef.current } });
      }, 200 + i * 120);
    });
    // Validate meta.json locally (no server lint needed)
    try {
      JSON.parse(metaContent);
      setLintMap(prev => ({ ...prev, meta: { ok: true, msg: '' } }));
    } catch (e: any) {
      setLintMap(prev => ({ ...prev, meta: { ok: false, msg: e.message || 'Invalid JSON' } }));
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [change]);

  // Listen for lint results, saved, saveError, folderPicked
  useEffect(() => {
    const handler = (event: MessageEvent) => {
      const msg = event.data;
      if (!msg) return;
      const mine = msg.payload?.requestId === requestIdRef.current;
      if (msg.type === 'lintResult') {
        if (!mine) return;
        const id = msg.payload?.id;
        if (id === 'deploy' || id === 'verify' || id === 'revert') {
          setLintMap(prev => ({ ...prev, [id]: { ok: !!msg.payload.ok, msg: msg.payload.msg || '' } }));
        }
      } else if (msg.type === 'saved' && msg.payload?.folderId && mine) {
        setSaving(false);
        setSaved({ folderRel: msg.payload.folderRel || msg.payload.folderId || '' });
      } else if (msg.type === 'saveError' && mine) {
        setSaving(false);
        setSaveError(msg.payload?.msg || 'Save failed.');
      } else if (msg.type === 'folderPicked' && mine) {
        setLocation(msg.payload?.path || msg.payload?.folderRel || '');
      } else if (msg.type === 'commitResult' && mine) {
        setCommitting(false);
        if (msg.payload?.ok) {
          setCommitDone(true);
          setCommitError('');
        } else {
          setCommitError(msg.payload?.error || 'Commit failed.');
        }
      }
    };
    window.addEventListener('message', handler);
    return () => window.removeEventListener('message', handler);
  }, []);

  useEffect(() => {
    const root = document.documentElement;
    const syncTheme = () => setIsLightTheme(root.dataset.theme === 'light');
    syncTheme();

    const observer = new MutationObserver(syncTheme);
    observer.observe(root, { attributes: true, attributeFilter: ['data-theme'] });
    return () => observer.disconnect();
  }, []);

  const handleSave = useCallback(() => {
    setSaving(true);
    setSaveError('');
    postMsg({
      type: 'saveChange',
      payload: {
        changeName: change.changeName,
        deploySql: editMap.deploy ?? change.deploySql,
        verifySql: editMap.verify ?? change.verifySql,
        revertSql: editMap.revert ?? change.revertSql,
        metaJson: editMap.meta ?? metaContent,
        location: location.trim(),
        requestId: requestIdRef.current,
      },
    });
  }, [change, location, metaContent, editMap]);

  const handleCopy = useCallback(() => {
    navigator.clipboard.writeText(effectiveSql(activeTab)).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    });
  }, [activeTab, editMap, sqlMap]);

  const handleBrowse = useCallback(() => {
    postMsg({ type: 'browseFolder', payload: { requestId: requestIdRef.current } });
  }, []);

  const handleReveal = useCallback(() => {
    if (saved?.folderRel) postMsg({ type: 'revealFolder', payload: { folderRel: saved.folderRel } });
  }, [saved]);

  const handleCommit = useCallback(() => {
    if (!saved?.folderRel || committing || commitDone) return;
    setCommitting(true);
    setCommitError('');
    postMsg({ type: 'manualCommitAndPush', payload: { folderRel: saved.folderRel, requestId: requestIdRef.current } });
  }, [saved, committing, commitDone]);

  const handleClose = useCallback(() => {
    if (saved) {
      // Already saved — wipe the form and return to a fresh form state.
      postMsg({ type: 'cancel', payload: { form, reset: true } });
    } else {
      setShowDiscard(true);
    }
  }, [form, saved]);

  const handleDiscardConfirm = useCallback(() => {
    setShowDiscard(false);
    postMsg({ type: 'cancel', payload: { form, reset: true } });
  }, [form]);

  const handleDiscardCancel = useCallback(() => {
    setShowDiscard(false);
  }, []);

  const lint = lintMap[activeTab];
  const changeNameValid = !change.changeName || /^(R__)?[a-z][a-z0-9_]*$/.test(change.changeName);

  return (
    <div className="cc-screen">
      <div className="change-card">
        {/* Header */}
        <div className="cc-header">
          <div className="cc-icon">
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z"/></svg>
          </div>
          <div className="cc-title">
            <div className="cc-name-row">
              <div className="cc-name">{change.changeName || 'change'}</div>
              {isDanger && <span className="cc-chip cc-chip-danger">danger_</span>}
              {isRepeatable && <span className="cc-chip cc-chip-repeatable">R__ repeatable</span>}
            </div>
            {!changeNameValid && (
              <div className="cc-name-warn">⚠ Change name must start with a letter and contain only lowercase letters, digits, and underscores</div>
            )}
            <div className="cc-subtitle">Review SQL, then save to your workspace</div>
          </div>
        </div>

        {/* Save location */}
        <div className="cc-loc">
          <label>Save location (relative to workspace root)</label>
          <div className="cc-loc-row">
            <input
              type="text"
              className="cc-loc-input"
              value={location}
              onChange={e => setLocation(e.target.value)}
              placeholder="db/changes (leave empty for workspace setting)"
            />
            <button type="button" className="cc-browse-btn" onClick={handleBrowse} title="Browse folder">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#f59e0b" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z"/></svg>
              Browse
            </button>
          </div>
        </div>

        {/* SQL Tabs */}
        <div className="cc-tabs">
          {(['deploy', 'verify', 'revert', 'meta'] as SqlTab[]).map(tab => (
            <button
              key={tab}
              type="button"
              className={`cc-tab${activeTab === tab ? ' active' : ''}${tab === 'meta' ? ' cc-tab-meta' : ''}`}
              onClick={() => setActiveTab(tab)}
            >
              <span className="cc-tab-label">{tab === 'meta' ? 'meta.json' : `${tab}.sql`}</span>
              <span
                className={`cc-tab-copy${copiedTab === tab ? ' cc-tab-copy--copied' : ''}`}
                title={copiedTab === tab ? 'Copied!' : `Copy ${tab === 'meta' ? 'meta.json' : tab + '.sql'}`}
                onClick={e => {
                  e.stopPropagation();
                  navigator.clipboard.writeText(effectiveSql(tab)).then(() => {
                    setCopiedTab(tab);
                    setTimeout(() => setCopiedTab(null), 1500);
                  });
                }}
              >
                {copiedTab === tab ? (
                  <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="#4ade80" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round">
                    <polyline points="20 6 9 17 4 12"/>
                  </svg>
                ) : (
                  <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <rect x="9" y="9" width="13" height="13" rx="2" ry="2"/>
                    <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/>
                  </svg>
                )}
              </span>
            </button>
          ))}
        </div>

        {/* SQL display with syntax highlighting + edit mode */}
        <div className="cc-sql-wrap">
          <div className="cc-sql-toolbar">
            <button
              type="button"
              className={`cc-sql-btn${editing ? ' active' : ''}`}
              onClick={() => setEditing(e => !e)}
              title={editing ? 'View mode' : 'Edit SQL'}
            >
              {editing ? (
                <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/><circle cx="12" cy="12" r="3"/></svg>
              ) : (
                <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/></svg>
              )}
              {editing ? 'View' : 'Edit'}
            </button>
            <button
              type="button"
              className="cc-sql-btn"
              onClick={handleCopy}
              title="Copy to clipboard"
            >
              {copied ? (
                <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="#4ade80" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"/></svg>
              ) : (
                <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg>
              )}
              {copied ? 'Copied!' : 'Copy'}
            </button>
          </div>
          {editing ? (
            <textarea
              className="cc-sql-editor"
              value={effectiveSql(activeTab)}
              onChange={e => setEditMap(prev => ({ ...prev, [activeTab]: e.target.value }))}
              spellCheck={false}
            />
          ) : (
            <SyntaxHighlighter
              language={activeTab === 'meta' ? 'json' : 'sql'}
              style={isLightTheme ? oneLight : vscDarkPlus}
              customStyle={{
                margin: 0,
                padding: '14px 16px',
                background: 'transparent',
                fontSize: '12.5px',
                lineHeight: '1.6',
                fontFamily: "ui-monospace,'Cascadia Code','JetBrains Mono',Consolas,monospace",
                overflow: 'auto',
                flex: 1,
                minHeight: 0,
                whiteSpace: 'pre-wrap',
                wordBreak: 'break-word',
                overflowX: 'hidden',
              }}
              wrapLongLines
            >
              {effectiveSql(activeTab)}
            </SyntaxHighlighter>
          )}
        </div>

        {/* Save error */}
        {saveError && <div className="cc-err">{saveError}</div>}

        {/* Footer: lint + actions */}
        <div className="cc-footer">
          <div className={`cc-lint${lint ? (lint.ok ? ' ok' : ' err') : ''}`}>
            {!lint && <span className="cc-lint-spinner" />}
            <span>
              {(() => {
                const fname = activeTab === 'meta' ? 'meta.json' : `${activeTab}.sql`;
                if (!lint) return `${fname} \u2014 linting\u2026`;
                if (lint.ok) return `${fname} \u2705`;
                return `${fname} \u274c ${lint.msg || 'has errors'}`;
              })()}
            </span>
          </div>
          <div className="cc-footer-btns">
            <button type="button" className="cc-btn danger" onClick={handleClose}>
              {saved ? 'Close' : '\u2715 Cancel'}
            </button>
            {!saved && (
              <button
                type="button"
                className="cc-btn primary"
                onClick={handleSave}
                disabled={saving || !changeNameValid}
                title={!changeNameValid ? 'Fix change name before saving' : undefined}
              >
                {saving ? 'Saving\u2026' : '\u{1F4BE} Save to workspace'}
              </button>
            )}
          </div>
        </div>

        {/* Saved confirmation */}
        {saved && (
          <div className="cc-saved">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"/></svg>
            <span>Saved to</span>
            <span className="cc-saved-path">{saved.folderRel}</span>
            <button type="button" className="cc-btn small" onClick={handleReveal}>Reveal in Explorer</button>
            <button
              type="button"
              className={`cc-btn small cc-btn-commit${commitDone ? ' done' : ''}`}
              onClick={handleCommit}
              disabled={committing || commitDone}
              title={commitDone ? 'Committed & pushed' : 'Commit & push to configured git remote'}
            >
              {/* GitHub icon */}
              <svg width="13" height="13" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
                <path d="M12 0C5.37 0 0 5.37 0 12c0 5.31 3.435 9.795 8.205 11.385.6.105.825-.255.825-.57 0-.285-.015-1.23-.015-2.235-3.015.555-3.795-.735-4.035-1.41-.135-.345-.72-1.41-1.23-1.695-.42-.225-1.02-.78-.015-.795.945-.015 1.62.87 1.845 1.23 1.08 1.815 2.805 1.305 3.495.99.105-.78.42-1.305.765-1.605-2.67-.3-5.46-1.335-5.46-5.925 0-1.305.465-2.385 1.23-3.225-.12-.3-.54-1.53.12-3.18 0 0 1.005-.315 3.3 1.23.96-.27 1.98-.405 3-.405s2.04.135 3 .405c2.295-1.56 3.3-1.23 3.3-1.23.66 1.65.24 2.88.12 3.18.765.84 1.23 1.905 1.23 3.225 0 4.605-2.805 5.625-5.475 5.925.435.375.81 1.095.81 2.22 0 1.605-.015 2.895-.015 3.3 0 .315.225.69.825.57A12.02 12.02 0 0 0 24 12c0-6.63-5.37-12-12-12z"/>
              </svg>
              {commitDone ? 'Committed ✓' : committing ? 'Committing…' : 'Commit'}
            </button>
          </div>
        )}
        {commitError && (
          <div className="cc-err" style={{ margin: '0 14px 8px' }}>
            ⚠ Commit failed: {commitError}
            <button type="button" style={{ marginLeft: 8, fontSize: 11, cursor: 'pointer', background: 'none', border: 'none', color: 'inherit', textDecoration: 'underline' }} onClick={() => setCommitError('')}>Dismiss</button>
          </div>
        )}
      </div>

      {/* Discard warning modal */}
      {showDiscard && (
        <div className="cc-discard-overlay">
          <div className="cc-discard-modal">
            <div className="cc-discard-icon">&#x26A0;</div>
            <div className="cc-discard-title">Discard unsaved changes?</div>
            <div className="cc-discard-msg">Generated SQL has not been saved. You'll be taken back to the form to start over.</div>
            <div className="cc-discard-btns">
              <button type="button" className="cc-btn" onClick={handleDiscardCancel}>Keep editing</button>
              <button type="button" className="cc-btn danger" onClick={handleDiscardConfirm}>Discard</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
