import React, { useState } from 'react';
import {
  BlockedIcon, ChevronDownIcon, ChevronRightIcon, LockIcon, RenameIcon, ShieldAlertIcon, TrashIcon, WarningTriangleIcon,
} from '@salilvnair/dui';

export default function GettingStartedPage() {
  return (
    <div style={{
      flex: 1, overflowY: 'auto', padding: '24px 28px',
      background: 'var(--bg-primary)', color: 'var(--text-primary)',
      fontFamily: 'var(--vscode-font-family, system-ui, sans-serif)',
    }}>
      {/* ── Header ── */}
      <div style={{ marginBottom: 28 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 6 }}>
          <span style={{ fontSize: 22, lineHeight: 1 }}>✦</span>
          <h1 style={{ margin: 0, fontSize: 22, fontWeight: 800, letterSpacing: '-0.4px', color: 'var(--text-primary)' }}>
            Quick Start
          </h1>
        </div>
        <p style={{ margin: 0, fontSize: 12, color: 'var(--text-secondary)' }}>
          DMCR v1.1.0 — Database Management &amp; Change Request for PostgreSQL
        </p>
      </div>

      {/* 1. What is DMCR */}
      <Section title="What is DMCR?" color="#6366f1">
        <p style={{ margin: '0 0 12px', fontSize: 13, color: 'var(--text-secondary)', lineHeight: 1.65 }}>
          DMCR is a VS Code-native database migration and change-request tool built for PostgreSQL teams.
          It generates <strong style={{ color: 'var(--text-primary)' }}>deploy / verify / revert</strong> SQL
          from natural language, tracks every change in a PostgreSQL registry, and ships with a
          built-in terminal runner — no separate CLI installation needed.
        </p>
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6 }}>
          {(['PostgreSQL', 'Flyway-inspired', 'Advisory Locking', 'Transactional', 'AI-Assisted',
            'Cross-Platform', 'deploy / verify / revert', 'Danger Folder Safety', 'Release Tags',
            'Schema Explorer', 'Schema Diff', 'MCP-ready'] as const).map(l => (
            <Chip key={l} label={l} color={CHIP_COLORS[l] ?? '#818cf8'} />
          ))}
        </div>
      </Section>

      {/* 2. Comparison */}
      <Section title="DMCR vs Flyway vs Sqitch" color="#a78bfa">
        <div style={{ overflowX: 'auto' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 12 }}>
            <thead>
              <tr style={{ background: 'rgba(99,102,241,0.10)' }}>
                <Th>Feature</Th><Th accent="#6366f1">DMCR</Th><Th>Flyway</Th><Th>Sqitch</Th>
              </tr>
            </thead>
            <tbody>
              {COMPARISON.map(r => <CompRow key={r.feature} {...r} />)}
            </tbody>
          </table>
        </div>
      </Section>

      {/* 3. Setup */}
      <Section title="Setup — Step by Step" color="#34d399">
        <StepBlock n={1} title="Install psql">
          <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
            <Row><Chip label="macOS" color="#60a5fa" /><Code>brew install postgresql</Code></Row>
            <Row><Chip label="Linux" color="#34d399" /><Code>sudo apt install postgresql-client</Code></Row>
            <Row>
              <Chip label="Windows" color="#f59e0b" />
              <span style={{ fontSize: 12, color: 'var(--text-secondary)' }}>
                Download from <span style={{ color: '#60a5fa', fontFamily: 'monospace' }}>postgresql.org/download</span> — the installer adds psql to PATH.
              </span>
            </Row>
          </div>
        </StepBlock>

        <StepBlock n={2} title="Configure — Settings → DMCR Config">
          <p style={{ margin: '0 0 8px', fontSize: 12, color: 'var(--text-secondary)', lineHeight: 1.6 }}>
            Open the <strong style={{ color: 'var(--text-primary)' }}>Settings</strong> tab and fill in
            DMCR Config. The connection URL (without password) is written to
            <Code>scripts/runner/dmcr.cfg</Code>. The password is stored separately in
            the OS Keychain via VS Code SecretStorage — it never touches disk as plaintext.
          </p>
          <CodeBlock>{`# scripts/runner/dmcr.cfg  (auto-generated by DMCR Config panel)
[dmcr]
env            = dev
changes_dir    = /absolute/path/to/your/changes
psql_path      = /opt/homebrew/bin/psql
lock_timeout   = 30s
statement_timeout = 5min

[dev]
# URL without password — password stored in OS Keychain as dmcr.devPassword
conn = postgresql://myuser@localhost:5432/mydb?sslmode=require

[prod]
conn = postgresql://myuser@prod-host:5432/mydb?sslmode=require`}</CodeBlock>
        </StepBlock>

        <StepBlock n={3} title="Initialise the registry">
          <p style={{ margin: '0 0 8px', fontSize: 12, color: 'var(--text-secondary)' }}>
            The registry is a set of tables DMCR creates in your database to track every deployed change.
          </p>
          <CodeBlock>{`# Runner tab — type: init
# or from terminal:

# macOS / Linux
/opt/homebrew/bin/bash scripts/runner/dmcr.sh init

# Windows
.\\scripts\\runner\\dmcr.ps1 init`}</CodeBlock>
          <p style={{ margin: '8px 0 0', fontSize: 12, color: 'var(--text-secondary)' }}>
            This creates <Code>dmcr.change_log</Code> and <Code>dmcr.tags</Code> in your database.
            Safe to run multiple times (idempotent).
          </p>
        </StepBlock>

        <StepBlock n={4} title="Generate your first change">
          <p style={{ margin: '0 0 8px', fontSize: 12, color: 'var(--text-secondary)', lineHeight: 1.6 }}>
            Pick a form from the top tab bar — <strong style={{ color: '#60a5fa' }}>DDL</strong> for
            table/index/constraint changes, <strong style={{ color: '#34d399' }}>DML</strong> for
            data seeds/updates, <strong style={{ color: '#f59e0b' }}>Insert</strong> for reference
            data, or <strong style={{ color: '#f472b6' }}>Freeform</strong> for anything else.
            Fill in the fields and click <strong style={{ color: 'var(--text-primary)' }}>Generate</strong>.
          </p>
          <p style={{ margin: '0', fontSize: 12, color: 'var(--text-secondary)' }}>
            DMCR creates a numbered change folder (e.g. <Code>001_create_users/</Code>) containing
            three files automatically.
          </p>
        </StepBlock>

        <StepBlock n={5} title="Review & deploy">
          <CodeBlock>{`# Check what would run (dry-run)
dmcr plan

# Deploy all pending changes
dmcr deploy

# Confirm everything verified
dmcr status`}</CodeBlock>
          <p style={{ margin: '8px 0 0', fontSize: 12, color: 'var(--text-secondary)' }}>
            DMCR acquires a PostgreSQL advisory lock before deploying so concurrent deploys are safe.
          </p>
        </StepBlock>
      </Section>

      {/* 4. Change Folder Anatomy */}
      <Section title="Change Folder Anatomy" color="#f59e0b">
        <p style={{ margin: '0 0 12px', fontSize: 13, color: 'var(--text-secondary)', lineHeight: 1.65 }}>
          Every DMCR change lives in a numbered folder inside your <Code>changes_dir</Code>.
          Naming convention: <Code>NNN_description/</Code> (versioned) or <Code>R__description/</Code> (repeatable).
        </p>
        <CodeBlock>{`changes/
├── 001_create_users/
│   ├── deploy.sql    ← forward migration (CREATE TABLE, ALTER, INSERT …)
│   ├── verify.sql    ← assertion run immediately after deploy (SELECT …)
│   └── revert.sql    ← undo deploy (DROP TABLE, DELETE …)
│
├── 002_add_email_index/
│   ├── deploy.sql
│   ├── verify.sql
│   └── revert.sql
│
└── R__refresh_materialized_views/
    └── deploy.sql    ← repeatable scripts — always re-run, no revert needed`}</CodeBlock>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(230px, 1fr))', gap: 10, marginTop: 14 }}>
          {FILE_ROLES.map(f => (
            <div key={f.file} style={{
              background: 'var(--bg-secondary)',
              border: `1px solid ${f.color}30`,
              borderRadius: 8, padding: '10px 12px',
            }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 7, marginBottom: 5 }}>
                <Chip label={f.file} color={f.color} />
              </div>
              <p style={{ margin: 0, fontSize: 11.5, color: 'var(--text-secondary)', lineHeight: 1.5 }}>{f.desc}</p>
            </div>
          ))}
        </div>
      </Section>

      {/* 5. AI Forms */}
      <Section title="AI-Powered Forms" color="#60a5fa">
        <p style={{ margin: '0 0 14px', fontSize: 13, color: 'var(--text-secondary)', lineHeight: 1.65 }}>
          DMCR has four forms, each producing a complete three-file change folder.
          Choose based on the type of change you're making:
        </p>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(260px, 1fr))', gap: 10 }}>
          {FORMS.map(f => (
            <div key={f.name} style={{
              background: 'var(--bg-secondary)',
              border: `1px solid ${f.color}25`,
              borderRadius: 9, padding: '12px 14px',
            }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 7 }}>
                <Chip label={f.name} color={f.color} />
                <span style={{ fontSize: 11, color: 'var(--text-secondary)' }}>{f.shortcut}</span>
              </div>
              <p style={{ margin: '0 0 7px', fontSize: 12, color: 'var(--text-primary)', fontWeight: 600 }}>{f.use}</p>
              <p style={{ margin: '0 0 8px', fontSize: 11.5, color: 'var(--text-secondary)', lineHeight: 1.5 }}>{f.desc}</p>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4 }}>
                {f.examples.map(e => (
                  <span key={e} style={{
                    fontSize: 10, fontFamily: 'monospace',
                    background: f.color + '18', color: f.color,
                    border: `1px solid ${f.color}33`,
                    padding: '1px 6px', borderRadius: 3,
                  }}>{e}</span>
                ))}
              </div>
            </div>
          ))}
        </div>
      </Section>

      {/* 6. Runner Commands */}
      <Section title="Runner Commands Reference" color="#22d3ee">
        <p style={{ margin: '0 0 12px', fontSize: 13, color: 'var(--text-secondary)', lineHeight: 1.65 }}>
          All commands work identically in the <strong style={{ color: 'var(--text-primary)' }}>Runner tab</strong>{' '}
          (just type the command name) and from a terminal using{' '}
          <Code>dmcr.sh</Code> (macOS/Linux) or <Code>dmcr.ps1</Code> (Windows).
        </p>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(220px, 1fr))', gap: 8 }}>
          {RUNNER_CMDS.map(({ cmd, desc, color }) => (
            <div key={cmd} style={{
              background: 'var(--bg-secondary)',
              border: '1px solid rgba(34,211,238,0.12)',
              borderRadius: 8, padding: '9px 12px',
              display: 'flex', alignItems: 'flex-start', gap: 10,
            }}>
              <span style={{
                display: 'inline-flex', alignItems: 'center',
                padding: '2px 8px', borderRadius: 4,
                fontSize: 11, fontWeight: 700, fontFamily: 'monospace',
                background: color + '1a', color, flexShrink: 0, marginTop: 1,
              }}>{cmd}</span>
              <span style={{ fontSize: 11.5, color: 'var(--text-secondary)', lineHeight: 1.5 }}>{desc}</span>
            </div>
          ))}
        </div>
        <div style={{ marginTop: 14, padding: '12px 14px', background: 'rgba(34,211,238,0.06)', borderRadius: 8, border: '1px solid rgba(34,211,238,0.15)' }}>
          <p style={{ margin: '0 0 6px', fontSize: 12, fontWeight: 700, color: '#22d3ee' }}>Common flags</p>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 5 }}>
            {FLAGS.map(f => (
              <div key={f.flag} style={{ display: 'flex', alignItems: 'baseline', gap: 10, fontSize: 12 }}>
                <Code>{f.flag}</Code>
                <span style={{ color: 'var(--text-secondary)' }}>{f.desc}</span>
              </div>
            ))}
          </div>
        </div>
      </Section>

      {/* 7. Schema Tools */}
      <Section title="Schema Explorer &amp; Schema Diff" color="#f472b6">
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
          <div style={{ background: 'var(--bg-secondary)', border: '1px solid rgba(244,114,182,0.2)', borderRadius: 9, padding: '12px 14px' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 7, marginBottom: 7 }}>
              <Chip label="Schema Explorer" color="#f472b6" />
            </div>
            <p style={{ margin: '0 0 8px', fontSize: 12, color: 'var(--text-secondary)', lineHeight: 1.55 }}>
              Browse tables, views, functions, and indexes in your active database.
              Click any object to see its DDL definition.
              Connects via your configured MCP server or directly via psql.
            </p>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: 5 }}>
              {['Tables', 'Views', 'Functions', 'Indexes', 'DDL preview'].map(l => <Chip key={l} label={l} color="#f472b6" />)}
            </div>
          </div>
          <div style={{ background: 'var(--bg-secondary)', border: '1px solid rgba(244,114,182,0.2)', borderRadius: 9, padding: '12px 14px' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 7, marginBottom: 7 }}>
              <Chip label="Schema Diff" color="#a78bfa" />
            </div>
            <p style={{ margin: '0 0 8px', fontSize: 12, color: 'var(--text-secondary)', lineHeight: 1.55 }}>
              Compare two environments (e.g. DEV vs PROD) side by side.
              AI highlights tables, functions, and views that are missing or drifted
              between environments.
            </p>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: 5 }}>
              {['DEV vs PROD', 'Missing objects', 'Drifted DDL', 'AI anomaly report'].map(l => <Chip key={l} label={l} color="#a78bfa" />)}
            </div>
          </div>
        </div>
      </Section>

      {/* 8. Danger Folder Safety */}
      <Section title="Danger Folder Safety" color="#f87171">
        <p style={{ margin: '0 0 12px', fontSize: 13, color: 'var(--text-secondary)', lineHeight: 1.65 }}>
          DMCR can automatically detect destructive SQL before it reaches your database.
          Configure danger rules in <strong style={{ color: 'var(--text-primary)' }}>Settings → Danger Rules</strong>.
        </p>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(250px, 1fr))', gap: 10 }}>
          {DANGER_RULES.map(r => (
            <div key={r.rule} style={{
              background: 'rgba(248,113,113,0.06)',
              border: '1px solid rgba(248,113,113,0.2)',
              borderRadius: 8, padding: '10px 12px',
            }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 7, marginBottom: 5 }}>
                <span style={{ display: 'inline-flex', alignItems: 'center', color: '#f87171' }}><r.icon size={14} /></span>
                <Chip label={r.rule} color="#f87171" />
              </div>
              <p style={{ margin: 0, fontSize: 11.5, color: 'var(--text-secondary)', lineHeight: 1.5 }}>{r.desc}</p>
            </div>
          ))}
        </div>
        <div style={{ marginTop: 12, padding: '10px 14px', background: 'rgba(248,113,113,0.06)', borderRadius: 8, border: '1px solid rgba(248,113,113,0.2)', fontSize: 12, color: 'var(--text-secondary)' }}>
          When a change folder triggers a danger rule, DMCR highlights it in the Runner tab and
          blocks deployment until you explicitly acknowledge and approve the destructive operation.
        </div>
      </Section>

      {/* 9. Multi-Environment */}
      <Section title="Multi-Environment Workflow" color="#86efac">
        <p style={{ margin: '0 0 12px', fontSize: 13, color: 'var(--text-secondary)', lineHeight: 1.65 }}>
          DMCR supports multiple environments in a single config. Switch environments in
          the <strong style={{ color: 'var(--text-primary)' }}>Active Environment</strong> dropdown
          (Settings → DMCR Config) or pass <Code>--env prod</Code> from the Runner.
        </p>
        <CodeBlock>{`# dmcr.cfg — multi-environment example
[dmcr]
env = dev           ← default active environment

[dev]
conn = postgresql://user@localhost:5432/myapp_dev

[st]
conn = postgresql://user@st-host:5432/myapp_st

[prod]
conn = postgresql://user@prod-host:5432/myapp_prod

# Passwords for each env stored separately in OS Keychain:
#   dmcr.devPassword / dmcr.stPassword / dmcr.prodPassword`}</CodeBlock>
        <div style={{ marginTop: 12 }}>
          <p style={{ margin: '0 0 8px', fontSize: 12, fontWeight: 600, color: 'var(--text-primary)' }}>Typical promotion flow:</p>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap' }}>
            {['Dev', '→', 'ST', '→', 'UAT', '→', 'Prod'].map((s, i) => (
              s === '→'
                ? <span key={i} style={{ fontSize: 16, color: 'var(--text-secondary)' }}>→</span>
                : <Chip key={s} label={s} color={ENV_COLORS[s] ?? '#818cf8'} />
            ))}
          </div>
          <p style={{ margin: '8px 0 0', fontSize: 12, color: 'var(--text-secondary)' }}>
            Run <Code>dmcr deploy --env st</Code> to promote the same changes folder
            to your ST environment without editing any config.
          </p>
        </div>
      </Section>

      {/* 10. Configuration reference */}
      <Section title="Configuration Reference" color="#fbbf24">
        <div style={{ overflowX: 'auto' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 12 }}>
            <thead>
              <tr style={{ background: 'rgba(251,191,36,0.08)' }}>
                <Th>Key</Th><Th>Default</Th><Th>Description</Th>
              </tr>
            </thead>
            <tbody>
              {CFG_KEYS.map(r => (
                <tr key={r.key} style={{ borderBottom: '1px solid rgba(255,255,255,0.05)' }}>
                  <td style={{ padding: '6px 12px' }}><Code>{r.key}</Code></td>
                  <td style={{ padding: '6px 12px', color: '#fbbf24', fontFamily: 'monospace', fontSize: 11 }}>{r.default}</td>
                  <td style={{ padding: '6px 12px', color: 'var(--text-secondary)' }}>{r.desc}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Section>

      {/* 11. MCP Integration */}
      <Section title="MCP &amp; AI Integration" color="#818cf8">
        <p style={{ margin: '0 0 12px', fontSize: 13, color: 'var(--text-secondary)', lineHeight: 1.65 }}>
          DMCR ships with a PostgreSQL MCP server (<Code>pgsql_mcp/</Code>) that exposes your
          schema to AI assistants. Connect it in <strong style={{ color: 'var(--text-primary)' }}>
          Settings → MCP</strong> and DMCR forms will automatically include schema context when
          generating SQL.
        </p>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(230px, 1fr))', gap: 10 }}>
          {MCP_TOOLS.map(t => (
            <div key={t.tool} style={{
              background: 'var(--bg-secondary)',
              border: '1px solid rgba(129,140,248,0.2)',
              borderRadius: 8, padding: '10px 12px',
            }}>
              <Chip label={t.tool} color="#818cf8" />
              <p style={{ margin: '6px 0 0', fontSize: 11.5, color: 'var(--text-secondary)', lineHeight: 1.5 }}>{t.desc}</p>
            </div>
          ))}
        </div>
      </Section>

      {/* 12. Tips */}
      <Section title="Tips &amp; Best Practices" color="#4ade80">
        <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
          {TIPS.map((t, i) => (
            <div key={i} style={{
              display: 'flex', gap: 12, alignItems: 'flex-start',
              background: 'var(--bg-secondary)',
              border: '1px solid rgba(74,222,128,0.12)',
              borderRadius: 8, padding: '10px 14px',
            }}>
              <span style={{
                minWidth: 22, height: 22, borderRadius: '50%',
                background: 'rgba(74,222,128,0.15)', color: '#4ade80',
                fontWeight: 700, fontSize: 11,
                display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0,
              }}>{i + 1}</span>
              <div style={{ fontSize: 12, color: 'var(--text-secondary)', lineHeight: 1.6 }}>
                {t}
              </div>
            </div>
          ))}
        </div>
      </Section>

      <div style={{ height: 32 }} />
    </div>
  );
}

/* ── Sub-components ── */

function Section({ title, color, children }: { title: string; color: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: 28 }}>
      <div style={{
        display: 'flex', alignItems: 'center', gap: 10, marginBottom: 14,
        paddingBottom: 8, borderBottom: `1px solid ${color}33`,
      }}>
        <span style={{ width: 3, height: 18, background: color, borderRadius: 2, flexShrink: 0, display: 'inline-block' }} />
        <h2 style={{ margin: 0, fontSize: 14, fontWeight: 700, color: 'var(--text-primary)', letterSpacing: '-0.2px' }}>
          {title}
        </h2>
      </div>
      {children}
    </div>
  );
}

function StepBlock({ n, title, children }: { n: number; title: string; children: React.ReactNode }) {
  const [open, setOpen] = useState(true);
  return (
    <div style={{ marginBottom: 14, border: '1px solid rgba(52,211,153,0.15)', borderRadius: 9, overflow: 'hidden' }}>
      <button
        onClick={() => setOpen(o => !o)}
        style={{
          width: '100%', display: 'flex', alignItems: 'center', gap: 10,
          padding: '9px 12px', background: 'rgba(52,211,153,0.06)',
          border: 'none', cursor: 'pointer', textAlign: 'left',
        }}
      >
        <span style={{
          width: 24, height: 24, borderRadius: '50%',
          background: '#059669', color: '#fff',
          fontWeight: 800, fontSize: 11,
          display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0,
        }}>{n}</span>
        <span style={{ fontSize: 13, fontWeight: 700, color: 'var(--text-primary)', flex: 1 }}>{title}</span>
        <span style={{ display: 'inline-flex', alignItems: 'center', color: 'var(--text-secondary)' }}>{open ? <ChevronDownIcon size={12} /> : <ChevronRightIcon size={12} />}</span>
      </button>
      {open && (
        <div style={{ padding: '12px 14px', borderTop: '1px solid rgba(52,211,153,0.10)' }}>
          {children}
        </div>
      )}
    </div>
  );
}

function Row({ children }: { children: React.ReactNode }) {
  return <div style={{ display: 'flex', alignItems: 'baseline', gap: 8 }}>{children}</div>;
}

function Chip({ label, color }: { label: string; color: string }) {
  return (
    <span style={{
      display: 'inline-flex', alignItems: 'center',
      padding: '2px 8px', borderRadius: 4,
      fontSize: 11, fontWeight: 600, fontFamily: 'monospace',
      background: color + '1a', color, border: `1px solid ${color}33`,
    }}>{label}</span>
  );
}

function Code({ children }: { children: React.ReactNode }) {
  return (
    <code style={{
      background: 'rgba(255,255,255,0.07)', padding: '1px 6px',
      borderRadius: 3, fontSize: 11.5, fontFamily: 'monospace', color: '#86efac',
    }}>{children}</code>
  );
}

function CodeBlock({ children }: { children: string }) {
  return (
    <pre style={{
      background: '#0d1117', color: '#4ade80',
      fontFamily: 'monospace', fontSize: 12,
      padding: '12px 14px', borderRadius: 8,
      margin: 0, overflowX: 'auto', whiteSpace: 'pre', lineHeight: 1.65,
      border: '1px solid rgba(74,222,128,0.15)',
    }}>{children}</pre>
  );
}

function Th({ children, accent }: { children: React.ReactNode; accent?: string }) {
  return (
    <th style={{
      padding: '7px 12px', textAlign: 'left', fontWeight: 700, fontSize: 11,
      color: accent ?? 'var(--text-secondary)',
      borderBottom: '1px solid rgba(255,255,255,0.08)', whiteSpace: 'nowrap',
    }}>{children}</th>
  );
}

function CompRow({ feature, dmcr, dmcrAccent, dmcrNote, flyway, sqitch, sqitchNote }: {
  feature: string; dmcr: string; dmcrAccent: string; dmcrNote?: string;
  flyway: string; sqitch: string; sqitchNote?: string;
}) {
  const td: React.CSSProperties = {
    padding: '6px 12px', fontSize: 12,
    borderBottom: '1px solid rgba(255,255,255,0.05)', color: 'var(--text-secondary)',
  };
  return (
    <tr>
      <td style={{ ...td, color: 'var(--text-primary)' }}>{feature}</td>
      <td style={td}>
        <span style={{ color: dmcrAccent, fontWeight: 700 }}>{dmcr}</span>
        {dmcrNote && <span style={{ marginLeft: 5, fontSize: 10, color: dmcrAccent, opacity: 0.75 }}>{dmcrNote}</span>}
      </td>
      <td style={td}><span style={{ color: flyway === '✓' ? '#34d399' : '#f87171', fontWeight: 700 }}>{flyway}</span></td>
      <td style={td}>
        <span style={{ color: sqitch === '✓' ? '#34d399' : '#f87171', fontWeight: 700 }}>{sqitch}</span>
        {sqitchNote && <span style={{ marginLeft: 5, fontSize: 10, color: '#34d399', opacity: 0.75 }}>{sqitchNote}</span>}
      </td>
    </tr>
  );
}

/* ── Data ── */

const CHIP_COLORS: Record<string, string> = {
  'PostgreSQL': '#60a5fa', 'Flyway-inspired': '#a78bfa', 'Advisory Locking': '#f472b6',
  'Transactional': '#34d399', 'AI-Assisted': '#f59e0b', 'Cross-Platform': '#22d3ee',
  'deploy / verify / revert': '#818cf8', 'Danger Folder Safety': '#f87171',
  'Release Tags': '#86efac', 'Schema Explorer': '#4ade80', 'Schema Diff': '#fb923c',
  'MCP-ready': '#e879f9',
};

const ENV_COLORS: Record<string, string> = {
  Dev: '#60a5fa', ST: '#34d399', UAT: '#f59e0b', Prod: '#f87171',
};

const COMPARISON = [
  { feature: 'AI-assisted SQL generation',      dmcr: '✓', dmcrAccent: '#34d399', flyway: '✗', sqitch: '✗', dmcrNote: 'DMCR only' },
  { feature: 'VS Code native UI',               dmcr: '✓', dmcrAccent: '#34d399', flyway: '✗', sqitch: '✗', dmcrNote: 'DMCR only' },
  { feature: 'deploy / verify / revert',        dmcr: '✓', dmcrAccent: '#34d399', flyway: '✗', sqitch: '✓', sqitchNote: 'Sqitch' },
  { feature: 'Advisory locking (PostgreSQL)',   dmcr: '✓', dmcrAccent: '#34d399', flyway: '✓', sqitch: '✗' },
  { feature: 'Repeatable migrations (R__*)',    dmcr: '✓', dmcrAccent: '#34d399', flyway: '✓', sqitch: '✗' },
  { feature: 'JSON output (CI-friendly)',       dmcr: '✓', dmcrAccent: '#34d399', flyway: '✓', sqitch: '✗' },
  { feature: 'Cross-platform (Win+Mac+Linux)',  dmcr: '✓', dmcrAccent: '#34d399', flyway: '✓', sqitch: '✓' },
  { feature: 'Danger folder safety',            dmcr: '✓', dmcrAccent: '#34d399', flyway: '✗', sqitch: '✗', dmcrNote: 'DMCR only' },
  { feature: 'Release tags',                    dmcr: '✓', dmcrAccent: '#34d399', flyway: '✓', sqitch: '✓' },
  { feature: 'Schema Explorer & Diff',          dmcr: '✓', dmcrAccent: '#34d399', flyway: '✗', sqitch: '✗', dmcrNote: 'DMCR only' },
  { feature: 'MCP / AI schema context',         dmcr: '✓', dmcrAccent: '#34d399', flyway: '✗', sqitch: '✗', dmcrNote: 'DMCR only' },
  { feature: 'No CLI install required',         dmcr: '✓', dmcrAccent: '#34d399', flyway: '✗', sqitch: '✗', dmcrNote: 'Runs inside VS Code' },
];

const FILE_ROLES = [
  { file: 'deploy.sql', color: '#34d399', desc: 'The forward migration — CREATE TABLE, ALTER COLUMN, INSERT reference data. Runs once per environment.' },
  { file: 'verify.sql', color: '#60a5fa', desc: 'Assertion that deploy succeeded — typically a SELECT that returns 1 row or a pg_catalog check. Runs immediately after deploy.' },
  { file: 'revert.sql', color: '#f87171', desc: 'Undo the deploy — DROP TABLE, DELETE, or ALTER to restore prior state. Only runs when you call revert.' },
];

const FORMS = [
  {
    name: 'DDL', color: '#60a5fa', shortcut: 'Schema changes',
    use: 'Tables, columns, indexes, constraints, sequences',
    desc: 'Describe the table or change in plain English. DMCR generates CREATE/ALTER/DROP with correct PostgreSQL syntax, plus an idempotent verify and a safe revert.',
    examples: ['CREATE TABLE', 'ADD COLUMN', 'DROP INDEX', 'ADD CONSTRAINT', 'CREATE SEQUENCE'],
  },
  {
    name: 'DML', color: '#34d399', shortcut: 'Data changes',
    use: 'UPDATE, DELETE, bulk data fixes',
    desc: 'Describe the data mutation. DMCR wraps it in a transaction with a pre-check verify (row count or value check) and a compensating revert DELETE/UPDATE.',
    examples: ['UPDATE status', 'DELETE stale rows', 'Backfill column', 'Fix bad data'],
  },
  {
    name: 'Insert', color: '#f59e0b', shortcut: 'Reference data',
    use: 'Seed data, lookup tables, config rows',
    desc: 'Insert one or more rows into a table. DMCR generates an upsert-safe INSERT (ON CONFLICT DO NOTHING) so re-running is safe, plus a verify SELECT.',
    examples: ['Seed config', 'Add enum values', 'Load lookup table', 'Initial admin user'],
  },
  {
    name: 'Freeform', color: '#f472b6', shortcut: 'Anything else',
    use: 'Functions, views, triggers, complex migrations',
    desc: 'Type any SQL or describe any change. DMCR acts as an AI pair-programmer: it writes the SQL, suggests a verify strategy, and generates a safe revert.',
    examples: ['CREATE FUNCTION', 'CREATE VIEW', 'GRANT/REVOKE', 'Multi-step migration'],
  },
];

const RUNNER_CMDS = [
  // Core
  { cmd: 'init',                    desc: 'Bootstrap DMCR registry tables in your database (idempotent)',               color: '#60a5fa' },
  { cmd: 'deploy',                  desc: 'Apply all pending deploy.sql scripts in order with advisory locking',        color: '#34d399' },
  { cmd: 'deploy --to <id|@tag>',   desc: 'Deploy only up to a specific change_id or @tag — useful for staged rollout', color: '#34d399' },
  { cmd: 'status',                  desc: 'Show deployed vs pending changes with tags and checksums',                   color: '#a78bfa' },
  { cmd: 'verify',                  desc: 'Re-run verify.sql for the last deployed change',                             color: '#4ade80' },
  { cmd: 'verify all',              desc: 'Re-run verify.sql for every applied change in order',                        color: '#4ade80' },
  { cmd: 'parse',                   desc: 'Validate SQL in a rolled-back transaction — safe, nothing persists in the DB', color: '#94a3b8' },
  { cmd: 'repeatable',              desc: 'Re-run all R__* scripts with changed checksums',                             color: '#86efac' },
  // Revert
  { cmd: 'revertLast',              desc: 'Roll back the most recently applied change using its revert.sql',            color: '#f87171' },
  { cmd: 'revert <id>',             desc: 'Roll back a specific change by ID (must be the latest applied)',             color: '#f87171' },
  { cmd: 'revert to <id|@tag>',     desc: 'Peel back all changes down to and including a target change or @tag',       color: '#f87171' },
  { cmd: 'revert list',             desc: 'List applied changes in reverse order — shows the revert sequence',          color: '#f87171' },
  // Inspect
  { cmd: 'plan',                    desc: 'Dry-run — list exactly what would run without touching the DB',              color: '#fbbf24' },
  { cmd: 'history',                 desc: 'Full deployment audit log with timestamps and actors',                       color: '#f59e0b' },
  { cmd: 'info',                    desc: 'Environment summary: applied count, pending count, registry health',         color: '#38bdf8' },
  { cmd: 'check',                   desc: 'Preflight — validate change file structure without deploying',               color: '#818cf8' },
  { cmd: 'show config',             desc: 'Print the resolved configuration (env, paths, connection redacted)',         color: '#22d3ee' },
  // Tags
  { cmd: 'tag list',                desc: 'List all release tags with their target change_id and timestamp',            color: '#f472b6' },
  { cmd: 'tag create <name>',       desc: 'Tag the current deployment state with a release name (e.g. v2.1)',          color: '#f472b6' },
  { cmd: 'tag delete <name>',       desc: 'Remove a release tag (does not affect applied changes)',                    color: '#f472b6' },
  // Repair & adoption
  { cmd: 'baseline',                desc: 'Mark an existing DB state as deployed — use when adopting DMCR on an existing schema', color: '#fb923c' },
  { cmd: 'repair --mark-applied',   desc: 'Manually mark a change as applied without running its deploy.sql',          color: '#e879f9' },
  { cmd: 'repair --mark-reverted',  desc: 'Manually mark a change as reverted without running its revert.sql',         color: '#e879f9' },
  { cmd: 'repair --checksums',      desc: 'Re-record checksums in the registry after an intentional file edit',        color: '#e879f9' },
];

const FLAGS = [
  { flag: '--env <name>',   desc: 'Override the active environment — e.g. deploy --env prod' },
  { flag: '--to <id|@tag>', desc: 'Deploy or revert up to a specific change_id or @tag target' },
  { flag: '--dry-run',      desc: 'Show pending changes without executing (plan mode for deploy)' },
  { flag: '--json',         desc: 'Machine-readable JSON output — useful for CI pipelines and scripting' },
  { flag: '--debug',        desc: 'Verbose diagnostic output for troubleshooting (or set DMCR_DEBUG=1)' },
  { flag: '-c <path>',      desc: 'Specify a custom dmcr.cfg path (or set DMCR_CONFIG env var)' },
];

const DANGER_RULES = [
  { rule: 'DROP TABLE',    icon: ShieldAlertIcon, desc: 'Blocks any change containing DROP TABLE outside of a revert.sql' },
  { rule: 'TRUNCATE',      icon: WarningTriangleIcon, desc: 'Flags TRUNCATE statements — data cannot be recovered without a backup' },
  { rule: 'DELETE all',    icon: TrashIcon, desc: 'Flags DELETE FROM table without a WHERE clause' },
  { rule: 'ALTER + DROP',  icon: BlockedIcon, desc: 'Flags ALTER TABLE … DROP COLUMN which is irreversible' },
  { rule: 'Prod guard',    icon: LockIcon, desc: 'Requires explicit --env prod confirmation before any deploy to production' },
  { rule: 'Custom rules',  icon: RenameIcon, desc: 'Add your own regex-based rules in Settings → Danger Rules' },
];

const MCP_TOOLS = [
  { tool: 'list_tables',       desc: 'Returns all tables in the active schema with column counts' },
  { tool: 'get_ddl',           desc: 'Returns the full CREATE statement for any table, view, or function' },
  { tool: 'list_functions',    desc: 'Lists all stored functions with signatures and return types' },
  { tool: 'run_query',         desc: 'Executes a read-only query and returns results as JSON' },
  { tool: 'compare_schemas',   desc: 'Diffs two environments and returns missing/drifted objects' },
  { tool: 'get_row_counts',    desc: 'Returns approximate row counts for all tables (fast, uses pg_stat)' },
];

const CFG_KEYS = [
  { key: 'env',              default: 'dev',           desc: 'Active environment — matches a section name ([dev], [prod], etc.)' },
  { key: 'changes_dir',      default: '(required)',    desc: 'Absolute path to your changes folder' },
  { key: 'psql_path',        default: '(from PATH)',   desc: 'Absolute path to the psql binary. Leave blank to rely on PATH.' },
  { key: 'lock_timeout',     default: '30s',           desc: 'Abort if waiting on a PostgreSQL advisory lock longer than this' },
  { key: 'statement_timeout',default: '5min',          desc: 'Abort any single SQL statement that runs longer than this' },
  { key: '[env] conn',       default: '(required)',    desc: 'PostgreSQL URL without password. Password stored in OS Keychain.' },
];

const TIPS = [
  <>Keep <Code>verify.sql</Code> fast — it runs after every deploy. A simple <Code>SELECT 1 FROM table WHERE … LIMIT 1</Code> is enough to confirm the object exists.</>,
  <>Use <strong>Release Tags</strong> (<Code>dmcr tag create v2.0</Code>) before and after each sprint so you can instantly see what changed between releases in <Code>dmcr status</Code>.</>,
  <>Never edit a <Code>deploy.sql</Code> after it has been deployed. The registry stores a checksum — changes will cause <Code>dmcr verify</Code> to fail. Use <Code>dmcr repair</Code> if unavoidable.</>,
  <>The <Code>changes_dir</Code> in your config can be an absolute path (good for monorepos with multiple services) or a workspace-relative path.</>,
  <>Commit your <Code>changes/</Code> folder to git. The <Code>.cfg</Code> file is safe to commit too — passwords never appear in it. Use <strong>Git Integration</strong> in settings to auto-commit on every generate.</>,
  <>Repeatable scripts (<Code>R__name/deploy.sql</Code>) are great for views, functions, and materialised views — they always reflect the latest definition and DMCR re-runs them on every deploy.</>,
  <>Use <Code>dmcr baseline</Code> when adopting DMCR on an existing database. It marks your current schema as "deployed" so DMCR only tracks new changes going forward.</>,
  <>The <strong>Schema Diff</strong> tab is the fastest way to spot drift between DEV and PROD before a deployment window — run it as the first step of any release checklist.</>,
];
